name: Build Font Minify Web Site

on:
  push:
    branches: ['site']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Build
        run: |
          npm install pnpm -g
          pnpm i
          pnpm build
          cp -r dist/. .
