name: Build Font Minify Web Site

on:
  push:
    branches: ['site']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: latest

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install pnpm -g
          pnpm i
          pnpm build
          cp -r dist/. .
